include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable rules that conflict with our architecture
    prefer_relative_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    
    # Enable additional rules for better code quality
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_statements: true
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat invalid assignments as errors
    invalid_assignment: error
    
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true