name: library_registration_app
description: "IQRA — Offline-first Flutter app for library administrators with a modern assistant-style interface."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.4.9
  connectivity_plus: ^6.0.5
  crypto: ^3.0.3
  csv: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  equatable: ^2.0.5
  excel: ^4.0.6
  ffi: ^2.1.0
  file_picker: ^10.2.4
  file_selector: ^1.0.3
  flutter_animate: ^4.3.0
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  json_annotation: any
  local_auth: ^2.1.7
  local_auth_android: any
  lottie: ^2.7.0
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  supabase_flutter: ^2.3.4
  uuid: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true
  assets:
    - IqraLogo.png

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "IqraLogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "IqraLogo.png"
  min_sdk_android: 23
  macos:
    generate: true
    image_path: "IqraLogo.png"
  windows:
    generate: true
    image_path: "IqraLogo.png"
  linux:
    generate: true
    image_path: "IqraLogo.png"
  web:
    generate: true
    image_path: "IqraLogo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

# Splash screen configuration moved to splash.yaml (run generator with --path=splash.yaml)
